import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavigation from '@/app/components/BottomNavigation'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

{/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/}
export const metadata: Metadata = {
  title: "Yokohama Aoba Pickles",
  description: "Generated by Tomo",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        {/*
        <div style={{ paddingBottom: '56px' }}>
          {children}
        </div>
        */}
        {/* paddingBottom を固定せず、コンテンツに任せるか、
            または BottomNavigation 側で高さ分を確保する */}
        <main>
          {children}
        </main>
        {/* ← これが重要！ */}
        <BottomNavigation />
      </body>
    </html>
  )
}
