/**
 * Filename: src/app/layout.tsx
 * Version : V1.1.0
 * Update  : 2026-02-08
 * Remarks :
 * V1.1.0 - BottomNavigation を client 版に差し替え。
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavigationClient from "@/app/components/BottomNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yokohama Aoba Pickles",
  description: "Generated by Tomo",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          {children}
        </main>

        {/* ← サンプル版 BottomNavigation を client component として呼び出す */}
        <BottomNavigationClient />
      </body>
    </html>
  );
}
